### ISSUE TITLE
Now Dev does not work with Angular

### ISSUE THREAD

**Issue by christopher-kiss** [vercel/vercel#2356]
Hi guys,

I'm following https://zeit.co/guides/deploying-angular-with-now and now dev does not work, following the guide exactly.

I get the following error when using `@now/static-build`. I've also tried using the canary build of the now-cli and I get the same issue.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
> [debug] [2019-05-16T20:27:54.095Z] Build process for package.json exited with 1
> Error! Builder exited with 1 before sending build result
> [debug] [2019-05-16T20:27:54.098Z] Error: Builder exited with 1 before sending build result
    at ChildProcess.onExit (C:\snapshot\repo\dist\index.js:1:1799681)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

Ideally, what I want is to use `@now/static` rather then the build, I don't really need now to build it for me when I can, so I have tried updating the routes to the build output.

```
{
    "version": 2,
    "name": "vision",
    "files": [
        "build"
    ],
    "builds": [
        {
            "src": "./build/**",
            "use": "@now/static"
        }
    ],
    "routes": [
        {
            "src": "/(favicon.ico|assets/.+|.+\\.css|.+\\.js)",
            "headers": {
                "cache-control": "max-age=31536000,immutable"
            },
            "dest": "/build/$1"
        },
        {
            "src": "/(.*).html",
            "headers": {
                "cache-control": "public,max-age=0,must-revalidate"
            },
            "dest": "/build/$1.html"
        },
        {
            "src": "/(.*)",
            "headers": {
                "cache-control": "public,max-age=0,must-revalidate"
            },
            "dest": "/build/index.html"
        }
    ]
}
```

This allows now dev to start successfully, but it doesn't load the angular app, it just shows the now file directory in the browser.

Any help would be appreciated.

**Comment by TooTallNate** [comment]
I think https://github.com/zeit/now-cli/pull/2358 should solve this problem.

**Comment by christopher-kiss** [comment]
@TooTallNate,

Thank you, will this also fix the `@now/static` only showing the now file directory instead of the angular app?

**Comment by td0m** [comment]
@TooTallNate Windows 10.0.18362.0, now 15.3.0 dev, still getting the same issue...
What I did
```bash
now init create-react-app
cd create-react-app
now dev
```

**Comment by TooTallNate** [comment]
Closing because this is a duplicate of https://github.com/zeit/now-cli/issues/2318.
