### ISSUE TITLE
[now-cli] upgrading to 16.3.0 breaks the routes

### ISSUE THREAD

**Issue by sudkumar** [vercel/vercel#3105]
**Summary**

I'm hosting a `static build` of my CRA bootstrapped app to Zeit. After upgrading to 16.3.0, my route redirection to root file stopped working. I was using `now.json.routes` to redirect all my dynamic routes to `index.html` file for frontend route handling. I am getting 404 errors while accessing routes other than index. Reverting back to **16.2.0** seams to fix this issue.

My `now.json` file
```json
{
  "name": "app-name",
  "routes": [
    { "src": "/static/(.*)", "dest": "/static/$1" },
    { "src": "/(.*\\.(js|json|png|jpg|ico|txt))", "dest": "/$1" },
    { "src": "/(.*)", "dest": "/" }
  ]
}
```

**Steps to reproduce**

Any `SPA` which is statically hosted with above `routes` configuration should reproduce the issue when deployed with `now-cli@16.3.0`.

**Comment by svobik7** [comment]
I am facing the same issue. Also downgrading to 16.2.0.

**Comment by sudkumar** [comment]
@svobik7 You mean, this is not working even in `16.2.0` ? It's working in my case.

**Comment by leo** [comment]
We have found the error and are working on a fix. We're also adding a test for this specific case, so that it won't ever happen again.

As in turns out, it only happens if `--local-config` is used.

**Comment by sudkumar** [comment]
@leo Thank you for your help. Keep up the good work 💪

**Comment by styfle** [comment]
Thank you for the bug report!

We released a fix for `--local-config` on the canary channel.

Can you try running `npm i -g now@canary` to confirm this version works for you? Thanks!

**Comment by sudkumar** [comment]
@styfle  Nope :( 

Still getting the same 404 error

```bash
$ now --version
16.1.4-canary.13
```

And, I after debugging a bit, I find out that `routes` configuration is not working at all. I tried changing the static assets route configuration to where it should not work, but it worked. i.e.

```diff
{
  "name": "app-name",
  "routes": [
-    { "src": "/static/(.*)", "dest": "/static/$1" },
+    { "src": "/static/(.*)", "dest": "/random_location/$1" },
    { "src": "/(.*\\.(js|json|png|jpg|ico|txt))", "dest": "/$1" },
    { "src": "/(.*)", "dest": "/" }
  ]
}
```

This should result in all static assets to `throw errors` but it DID NOT, which means that this configuration is not affecting the routing at all.

**Comment by sudkumar** [comment]
@styfle Please let me know if anyway I can help.

**Comment by styfle** [comment]
@sudkumar Is your code available for me to look at? Perhaps on GitHub?

This bug seems to be intermittent such that a second deployment will work properly.

**Comment by sudkumar** [comment]
@styfle It is a private repository but I can make it public for some time. Please have a look and let me know when you are done or need any further information.

**Comment by styfle** [comment]
@sudkumar 

I cloned the repo and deployed with now@canary just fine. Static assets are available.

Can you share the exact Now command with flags you are using to get the routes to fail?

**Comment by sudkumar** [comment]
@styfle Did you try to refresh the login page? The root URL `/` loads but `/login` will fail when refreshed.

I am using `deploy:testing` from package.json file.

**Comment by styfle** [comment]
@sudkumar Thanks! I released another canary with a fix. `npm i -g now@canary`

**Comment by sudkumar** [comment]
@styfle Thank you. I'll test and report.

**Comment by sudkumar** [comment]
@styfle Awesome. It's working
```bash
$ now --version
16.1.4-canary.14
```
