### ISSUE TITLE
Now + Next.js: "Please install typescript" error with --prod deployment

### ISSUE THREAD

**Issue by theBliz** [vercel/vercel#3109]
I have a staging/production environment on Zeit for a frontend application done in Next.js.
Last prod deployment was done 4 days ago, without issues.

Today I've merged staging into prod, but I get an error that blocks the deployment while building the application:
```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Please install typescript by running:
         npm install --save-dev typescript
If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files)
```
I'm not sure what is the reason why this error shows up now and not in the previous builds. I've checked the builds logs and nothing changed.

I could probably solve this by adding typescript as **prod dependency** instead of having it as devDependency in my package.json file, but I'm not sure why the error is happening now and wasn't there on the latest releases.

Another workaround would be to not use the **--prod flag** on the **production deployment** since the issue doesn't happen with the **staging deployment** that doesn't use the --prod flag.

This is the full deployment command I'm using
```
now --prod --token $ZEIT_TOKEN --local-config .now/now.production.json
```

I have a gut feeling that it might be connected to #3107 and #3105 

Any hints?

Ps: I've also open a [thread on spectrum](https://spectrum.chat/zeit/general/now-next-js-please-install-typescript-error-on-production-deployment~6cc5a743-0ca1-4e21-b45f-02a8ee0dcfb8) and seems I'm not the only one

**Comment by styfle** [comment]
Thank you for the bug report!

We released a fix for `--local-config` on the canary channel.

Can you try running `npm i -g now@canary` to confirm this version works for you? Thanks!

**Comment by theBliz** [comment]
@styfle I'm still having the same issue (_Please install typescript_) even when using `now@canary`.

This is my CI workflow
```
npm install --global --unsafe-perm now@canary
now --prod --token $ZEIT_TOKEN --local-config .now/now.production.json
``` 
and this is my `now.production.json`
```
{
    "version": 2,
    "name": "my-production-name",
    "alias": "myproductiondomain.com",
    "builds": [{ "src": "package.json", "use": "@now/next" }]
}
```

I've seen that also #3107 has been re-open, shall we move everything under the same thread?

**Comment by styfle** [comment]
> shall we move everything under the same thread?

Indeed, this is the same bug, thanks!

**Comment by theBliz** [comment]
for future reference, this issue is currently solved by using `now@canary`

```
npm install --global --unsafe-perm now@canary
now --prod --token $ZEIT_TOKEN --local-config .now/now.production.json
```
and `now.production.json`
```
{
    "version": 2,
    "name": "my-production-name",
    "alias": "myproductiondomain.com",
    "builds": [{ "src": "package.json", "use": "@now/next" }]
}
```
