### ISSUE TITLE
connecting server to subdomain

### ISSUE THREAD

**Issue by jjhesk** [vercel/vercel#3118]
how do i deploy a server and connecting to the subdomain in zeit hosted domain?
for example: api.mydomain.com
use the subdomain to map a custom ip and on the www domain map to zeit hosted html.
how to achieve that?

**Comment by styfle** [comment]
Hi @jjhesk 

~~You can use the `alias` key in now.json to assign one or more hostnames.~~

You can use the dashboard settings to assign domains: https://vercel.com/docs/v2/custom-domains

If you would like www to redirect, you can follow this blog post: https://vercel.com/blog/redirecting-domains

**Comment by TimPchelintsev** [comment]
Hi @jjhesk 
You need to [setup A record via now cli](https://zeit.co/docs/v2/advanced/domains/dns/#now-dns-add):
`now dns add <yourzeitdomain.com> <subdomain> A <ip>`

**Comment by cdedreuille** [comment]
I have the same issue. I created an A record like this
now dns add domain.com api.domain.com A <ip>
But for some reasons the subdomain always goes to the main site hosted on Vercel and not the external. It's like the A record is ignored.

On the admin panel I added api.domain.com to my project as if I don't do this, I get a 404.

Any idea what I'm doing wrong?

**Comment by cdedreuille** [comment]
Ok, just in case somebody has the same problem. I fixed it finding the solution [here](https://github.com/zeit/now/issues/3052#issuecomment-578453425)

When it says `now dns add <yourzeitdomain.com> <subdomain> A <ip>`
You actually have to put just the subdomain without the domain, so
`now dns add domain.com api A <ip>`

**Comment by cauldyclark15** [comment]
> Ok, just in case somebody has the same problem. I fixed it finding the solution [here](https://github.com/zeit/now/issues/3052#issuecomment-578453425)
> 
> When it says `now dns add <yourzeitdomain.com> <subdomain> A <ip>`
> You actually have to put just the subdomain without the domain, so
> `now dns add domain.com api A <ip>`

I think the issue still persist, in my case after adding a subdomain and points it to an external IP, trying to access it gives me this
![Screen Shot 2020-06-30 at 2 47 45 PM](https://user-images.githubusercontent.com/11132381/86093031-ec698380-bae0-11ea-9e8b-a20381d8c264.png)

**Comment by dimosmera** [comment]
Yes, we have the exact same issue. Why is this closed?
