### ISSUE TITLE
Cant Deploy next application using the zeit.co

### ISSUE THREAD

**Issue by piijt** [vercel/vercel#3421]
So I wrote a next application, and am trying to deploy it using the zeit.co and I get a really long list off errors, 

NPM version @6.9.0
Now version @ 16.6.3

Error log: 

Downloading 24 deployment files...
--
09:30:22 PM | Installing build runtime...
09:30:22 PM | Build runtime installed: 610.373ms
09:30:23 PM | Looking up build cache...
09:30:23 PM | WARNING: your application is being deployed in @now/next's legacy mode. http://err.sh/zeit/now/now-next-legacy-mode
09:30:23 PM | Installing dependencies...
09:30:23 PM | yarn install v1.17.3
09:30:24 PM | info No lockfile found.
09:30:24 PM | [1/4] Resolving packages...
09:30:25 PM | warning @truffle/hdwallet-provider > web3-provider-engine > ethereumjs-vm > merkle-patricia-tree > level-ws > xtend > object-keys@0.4.0:
09:30:26 PM | warning @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > json-rpc-engine > babel-preset-env > babel-plugin-check-es2015-constants > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
09:30:26 PM | warning @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > json-rpc-engine > babelify > babel-core > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
09:30:26 PM | warning next > @babel/runtime-corejs2 > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
09:30:27 PM | warning next > webpack > watchpack > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
09:30:28 PM | warning web3 > web3-core > @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
09:30:28 PM | [2/4] Fetching packages...
09:30:37 PM | info fsevents@1.2.9: The platform "linux" is incompatible with this module.
09:30:37 PM | info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
09:30:37 PM | [3/4] Linking dependencies...
09:30:40 PM | [4/4] Building fresh packages...
09:31:03 PM | success Saved lockfile.
09:31:03 PM | Done in 39.61s.
09:31:03 PM | Running "yarn run now-build"
09:31:03 PM | yarn run v1.17.3
09:31:03 PM | $ NODE_OPTIONS=--max_old_space_size=3000 next build --lambdas
09:31:04 PM | [8:31:04 PM] Compiling client
09:31:23 PM | Browser assets sizes after gzip:
09:31:23 PM | 1.04 kB  .next/static/vo5j****/pages/_app.js
09:31:23 PM | 2.42 kB  .next/static/vo5j****/pages/_error.js
09:31:23 PM | 25.2 kB  .next/static/vo5j****/pages/ideas/new.js
09:31:23 PM | 14.1 kB  .next/static/vo5j****/pages/ideas/requests.js
09:31:23 PM | 24.6 kB  .next/static/vo5j****/pages/ideas/requests/new.js
09:31:23 PM | 26.7 kB  .next/static/vo5j****/pages/ideas/show.js
09:31:23 PM | 13.7 kB  .next/static/vo5j****/pages/index.js
09:31:23 PM | 248 B  .next/static/vo5j****/pages/newidea.js
09:31:23 PM | 418 kB  .next/static/chunks/commons.0474****.js
09:31:23 PM | 5.41 kB  .next/static/runtime/main-7470****.js
09:31:23 PM | 737 B  .next/static/runtime/webpack-4265****.js
09:31:23 PM | [8:31:23 PM] Compiled client in 19s
09:31:23 PM | [8:31:23 PM] Compiling server
09:32:13 PM | [8:32:13 PM] Compiled server in 49s
09:32:13 PM | > Emitted warnings from webpack
09:32:13 PM | ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
09:32:13 PM | at Compilation.reportDependencyErrorsAndWarnings (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:1359:23)
09:32:13 PM | at Compilation.finish (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:1165:9)
09:32:13 PM | at hooks.make.callAsync.err (/zeit/36547fec/node_modules/webpack/lib/Compiler.js:544:17)
09:32:13 PM | at _err0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
09:32:13 PM | at Promise.all.then (/zeit/36547fec/node_modules/webpack/lib/DynamicEntryPlugin.js:74:20)
09:32:13 PM | at process._tickCallback (internal/process/next_tick.js:68:7)
09:32:13 PM | at CommonJsRequireContextDependency.getWarnings (/zeit/36547fec/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
09:32:13 PM | at Compilation.reportDependencyErrorsAndWarnings (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:1354:24)
09:32:13 PM | at Compilation.finish (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:1165:9)
09:32:13 PM | at hooks.make.callAsync.err (/zeit/36547fec/node_modules/webpack/lib/Compiler.js:544:17)
09:32:13 PM | at _err0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
09:32:13 PM | at Promise.all.then (/zeit/36547fec/node_modules/webpack/lib/DynamicEntryPlugin.js:74:20)
09:32:13 PM | at process._tickCallback (internal/process/next_tick.js:68:7) ModuleNotFoundError: Module not found: Error: Can't resolve '../build/Release/bufferutil' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | at factory.create (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:821:10)
09:32:13 PM | at factory (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
09:32:13 PM | at resolver (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
09:32:13 PM | at asyncLib.parallel (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:2830:7
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:6877:13
09:32:13 PM | at normalResolver.resolve (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
09:32:13 PM | at doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
09:32:13 PM | resolve '../build/Release/bufferutil' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./lib)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./build/Release/bufferutil)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/bufferutil doesn't exist ModuleNotFoundError: Module not found: Error: Can't resolve '../build/Release/validation' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | at factory.create (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:821:10)
09:32:13 PM | at factory (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
09:32:13 PM | at resolver (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
09:32:13 PM | at asyncLib.parallel (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:2830:7
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:6877:13
09:32:13 PM | at normalResolver.resolve (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
09:32:13 PM | at doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
09:32:13 PM | resolve '../build/Release/validation' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./lib)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./build/Release/validation)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/Release/validation doesn't exist ModuleNotFoundError: Module not found: Error: Can't resolve '../build/default/bufferutil' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | at factory.create (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:821:10)
09:32:13 PM | at factory (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
09:32:13 PM | at resolver (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
09:32:13 PM | at asyncLib.parallel (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:2830:7
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:6877:13
09:32:13 PM | at normalResolver.resolve (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
09:32:13 PM | at doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
09:32:13 PM | resolve '../build/default/bufferutil' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./lib)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./build/default/bufferutil)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/bufferutil doesn't exist ModuleNotFoundError: Module not found: Error: Can't resolve '../build/default/validation' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | at factory.create (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:821:10)
09:32:13 PM | at factory (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
09:32:13 PM | at resolver (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
09:32:13 PM | at asyncLib.parallel (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:2830:7
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:6877:13
09:32:13 PM | at normalResolver.resolve (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
09:32:13 PM | at doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
09:32:13 PM | resolve '../build/default/validation' in '/zeit/36547fec/node_modules/@web3-js/websocket/lib'
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./lib)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/@web3-js/websocket/package.json (relative path: ./build/default/validation)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/@web3-js/websocket/build/default/validation doesn't exist
09:32:13 PM | ModuleNotFoundError: Module not found: Error: Can't resolve './build/Release/scrypt' in '/zeit/36547fec/node_modules/scrypt'
09:32:13 PM | at factory.create (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:821:10)
09:32:13 PM | at factory (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
09:32:13 PM | at resolver (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
09:32:13 PM | at asyncLib.parallel (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:2830:7
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:6877:13
09:32:13 PM | at normalResolver.resolve (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
09:32:13 PM | at doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
09:32:13 PM | resolve './build/Release/scrypt' in '/zeit/36547fec/node_modules/scrypt'
09:32:13 PM | using description file: /zeit/36547fec/node_modules/scrypt/package.json (relative path: .)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/scrypt/package.json (relative path: ./build/Release/scrypt)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/scrypt/build/Release/scrypt doesn't exist ModuleNotFoundError: Module not found: Error: Can't resolve 'electron' in '/zeit/36547fec/node_modules/swarm-js/node_modules/got'
09:32:13 PM | at factory.create (/zeit/36547fec/node_modules/webpack/lib/Compilation.js:821:10)
09:32:13 PM | at factory (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
09:32:13 PM | at resolver (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
09:32:13 PM | at asyncLib.parallel (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:2830:7
09:32:13 PM | at /zeit/36547fec/node_modules/neo-async/async.js:6877:13
09:32:13 PM | at normalResolver.resolve (/zeit/36547fec/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
09:32:13 PM | at doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
09:32:13 PM | at hook.callAsync (/zeit/36547fec/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
09:32:13 PM | at _fn0 (eval at create (/zeit/36547fec/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
09:32:13 PM | at resolver.doResolve (/zeit/36547fec/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
09:32:13 PM | resolve 'electron' in '/zeit/36547fec/node_modules/swarm-js/node_modules/got'
09:32:13 PM | Parsed request is a module
09:32:13 PM | using description file: /zeit/36547fec/node_modules/swarm-js/node_modules/got/package.json (relative path: .)
09:32:13 PM | resolve as module
09:32:13 PM | looking for modules in /zeit/36547fec/node_modules/next/node_modules
09:32:13 PM | using description file: /zeit/36547fec/node_modules/next/package.json (relative path: ./node_modules)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/next/package.json (relative path: ./node_modules/electron)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/next/node_modules/electron doesn't exist
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/got/node_modules doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/got/undefined doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/node_modules doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/undefined doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/undefined doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/node_modules/node_modules doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/node_modules/undefined doesn't exist or is not a directory
09:32:13 PM | /zeit/36547fec/undefined doesn't exist or is not a directory
09:32:13 PM | /zeit/node_modules doesn't exist or is not a directory
09:32:13 PM | /zeit/undefined doesn't exist or is not a directory
09:32:13 PM | /node_modules doesn't exist or is not a directory
09:32:13 PM | /undefined doesn't exist or is not a directory
09:32:13 PM | looking for modules in /zeit/36547fec/node_modules/swarm-js/node_modules
09:32:13 PM | using description file: /zeit/36547fec/node_modules/swarm-js/package.json (relative path: ./node_modules)
09:32:13 PM | using description file: /zeit/36547fec/node_modules/swarm-js/package.json (relative path: ./node_modules/electron)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron doesn't exist
09:32:13 PM | looking for modules in /zeit/36547fec/node_modules
09:32:13 PM | using description file: /zeit/36547fec/package.json (relative path: ./node_modules)
09:32:13 PM | using description file: /zeit/36547fec/package.json (relative path: ./node_modules/electron)
09:32:13 PM | no extension
09:32:13 PM | /zeit/36547fec/node_modules/electron doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron.wasm doesn't exist
09:32:13 PM | .wasm
09:32:13 PM | /zeit/36547fec/node_modules/electron.wasm doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron.js doesn't exist
09:32:13 PM | .js
09:32:13 PM | /zeit/36547fec/node_modules/electron.js doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron.mjs doesn't exist
09:32:13 PM | .mjs
09:32:13 PM | /zeit/36547fec/node_modules/electron.mjs doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron.jsx doesn't exist
09:32:13 PM | .jsx
09:32:13 PM | /zeit/36547fec/node_modules/electron.jsx doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron.json doesn't exist
09:32:13 PM | .json
09:32:13 PM | /zeit/36547fec/node_modules/electron.json doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/swarm-js/node_modules/electron doesn't exist
09:32:13 PM | as directory
09:32:13 PM | /zeit/36547fec/node_modules/electron doesn't exist
09:32:13 PM | > Build error occured
09:32:13 PM | Error: > Build failed because of webpack errors
09:32:13 PM | at Object.build [as default] (/zeit/36547fec/node_modules/next/dist/build/index.js:42:15)
09:32:13 PM | at process._tickCallback (internal/process/next_tick.js:68:7)
09:32:13 PM | error Command failed with exit code 1.
09:32:13 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
09:32:13 PM | Error: Exited with 1
09:32:13 PM | at ChildProcess.child.on (/zeit/922cd6377aef4b37/.build-utils/.builder/node_modules/@now/next/dist/index.js:46408:24)
09:32:13 PM | at emitTwo (events.js:126:13)
09:32:13 PM | at ChildProcess.emit (events.js:214:7)
09:32:13 PM | at maybeClose (internal/child_process.js:925:16)
09:32:13 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
09:32:13 PM | worker exited with code 20 and signal null
09:32:15 PM | done

**Comment by ericelliott** [comment]
I'm getting non-deterministic build failures. Not sure if it's related to this problem, but just in case:

I keep getting failures trying to deploy the latest version of my app. I've been trying to figure out what's going on, but it seems like the build is not failing in a deterministic way. Sometimes I get `npm EEXIST error`, but the file that I get it for varies between deployment attempts. Other times, I get errors like this:

```
Warning: Failed to resolve dependency fast-crc32c:
2019-12-12T23:41:35.225Z  Cannot find module 'fast-crc32c' loaded from /zeit/722987df/node_modules/hash-stream-validation/index.js
...
Warning: Failed to resolve dependency worker_threads:
2019-12-12T23:41:35.225Z  Cannot find module 'worker_threads' loaded from /zeit/722987df/node_modules/write-file-atomic/index.js
...
```

I am using now@16.6.3 and npm@6.13.4.

I was able to successfully deploy just by retrying a bunch of times until it worked. I was also able to deploy another, less complex app. These failures seem like they could be race conditions in the deploy?

cc @leo

**Comment by piijt** [comment]
@ericelliott, alright I guess I will try to deploy it a whole bunch of times and cross my fingers, I am using npm@10.16.2 - and I don't think I can go below v8.0.5 or something like that because of my application librarys. I was also able to deploy some simple application but this just wont seem to work. Wish me luck! And keep more solutions coming just in case :p

**Comment by ericelliott** [comment]
@piijt As I said, I was able to get my deploy to work using `now@16.6.3` and `npm@6.13.4` but I'm still getting intermittent deploy failures. A deploy will fail, I'll change nothing, redeploy, and eventually it works.

What I'm seeing looks like race condition bugs to me -- I'm not sure if it's a problem with npm, or with now's deploy scripts.

**Comment by codinronan** [comment]
We've been having serious problems with Now recently as well and are now making plans to move off to another host. 

In the meantime, the problems we've been seeing range from:

* When using "now" to deploy it is totally random if the environment variables actually make it into the final build or not
* When using "now" it is also totally random if the deployed build will actually work - the errors are always "EA_AGAIN" and the code cannot call out to external APIs. Deploying again and again and again usually fixes it... eventually. For a day or so. Then we get to try again.

YES I am using Now v1.
YES I am using Docker.
I am using Next.js v9 (latest)
Now v16.7.0
Yarn, latest
node + npm, 10.15 and whatever version of npm comes with it.

I'm going to create a separate issue. This command no longer works as of yesterday:

```
now -t $NOW_TOKEN --scope ourApp -e CUST_ENV=alpha -e APP_HOSTNAME=the.host.name -e HEALTH_KEY -e BUGSNAG_BROWSER_API_KEY -e BUGSNAG_SERVER_API_KEY -e STRIPE_KEY
```

At no point are these variables available anywhere in the docker image, nor in the build stack, and yet interestingly when spitting out "process.env" from within a file in "/pages/api", the variables are there and defined... so apparently they are only being made available when the final step to launch the server is executed. This is a change and they have for 2 years been available at build time.

I don't know what has happened and I've already lost 2 days on this. I initially chose Now because everything "just worked". That hasn't been true in a long time.

**Comment by styfle** [comment]
Thanks for reporting this issue!

Indeed this was caused by a race condition that was happening intermittently for projects with large a large cache (typically node_modules).

The issue was fixed a few days ago so you should no longer experience any problems.

You might need to use `now -f` or the "Rebuild" button in web interface to force a build with a new cache.

Thanks!

**Comment by ericelliott** [comment]
@styfle Thanks so much! Keep up the great work. =)

**Comment by danhollick** [comment]
~@styfle I'm still getting these errors, despite using `--force` or `-f`. 
They started just after I updated the `engine` in `package.json` to use `12.x`~

Appeared to be an issue on my side. NVM version mismatch
