### ISSUE TITLE
Now CLI 17.0.1 seems to ignore .env vars in dev

### ISSUE THREAD

**Issue by flintinatux** [vercel/vercel#3758]
I upgraded `now` to 17.0.1 this evening, and my `.env` vars seem to be ignored.  The first red flag was a "parse error" on the `mongodb` URI:
```
$ now dev
Now CLI 17.0.1 dev (beta) — https://zeit.co/feedback
e> Running Dev Command “next dev --port $PORT”
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:64704 ...
Defining routes from exportPathMap
> Ready! Available at http://localhost:3000
[ ready ] compiled successfully - ready on http://localhost:64704
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:64704
[ event ] build page: <REDACTED>
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:64704
MongoParseError: URI malformed, cannot be parsed
    at parseConnectionString
```
If I log that env var, it comes up `undefined`:
```js
const { MONGO_URL } = process.env
console.log({ MONGO_URL })
```
```
[ ready ] compiled successfully - ready on http://localhost:3000
{ MONGO_URL: undefined }
```
Downgrading to 16.7.3 immediately fixed it.  Was there a breaking change in how dev env vars are handled that I might have missed?

**Comment by bowswung** [comment]
I have encountered exactly the same issue.  I have checked what `process.env` contains, and it has all the normal stuff + build environment variables (from `.env.build`) but nothing from `.env`.

**Comment by sambecker** [comment]
Encountered exact same issue. In case it helps anyone else, going to Zeit project settings dashboard and changing the `Framework Preset` from `Next` to `Other` made my .env variables work locally when running `now dev`. Not sure why.

**Comment by lcdproductions** [comment]
another embarrassing release from the zeit team. causes customer pain, no response for days and chastises customers when they reach out for support or to voice frustration on a product just plain not working. really growing tired of their business practices.

**Comment by rootedsoftware** [comment]
```
const { MONGO_URL } = process.env
```

You can't destructure the process.env. vars.
https://nextjs.org/docs/api-reference/next.config.js/environment-variables

"Next.js will replace process.env.customKey with 'my-value' at build time. Trying to destructure process.env variables won't work due to the nature of webpack [DefinePlugin](https://webpack.js.org/plugins/define-plugin/)."

**Comment by flintinatux** [comment]
@c316, thank you so much.  That's probably exactly what it is.  I guess that's changed recently, and I just missed it.  I'll try it out soon.

**Comment by alex-grover** [comment]
pretty sure the issue exists even if you reference the env vars without destructuring

**Comment by fromi** [comment]
I remove the process.env destructuring from my code, and **I am still having the issue** with now cli 17.0.3 : nothing gets injected in my /api routes.
So, I guess I must rollback once more to v16.

**Comment by jacobbroughton** [comment]
I'm having this issue too, glad I'm not crazy lol

**Comment by jacobbroughton** [comment]
> I remove the process.env destructuring from my code, and **I am still having the issue** with now cli 17.0.3 : nothing gets injected in my /api routes.
> So, I guess I must rollback once more to v16.

How do you fall back to another version? Can't find it in the docs, thanks!

**Comment by jos-** [comment]
Possibly related: when deploying from my local machine I can pass env variables using `now -e MY_VARIABLE=my_value`. Also works in a local Docker container using `now -e ... --token=... `. However, on Bitbucket Pipelines with exactly the same Docker container (`node:latest`, Debian Linux 9) and exactly the same command this fails and the value of the variable is always `undefined`.

@jlbroughton88 you can downgrade using `npm -i -g now@16`, but v16 handles the build step differently.

**Comment by alejalapeno** [comment]
The docs have changed from `.env` to `.env.build` under the instructions for [During Local Development](https://zeit.co/docs/v2/build-step#during-local-development). Allowing a bare `.env` has been industry standard and this is a strange requirement.

This and several other recent breaking changes to 17.x all seem to stem from a goal to kill off `now dev`: https://github.com/zeit/now/pull/3748

**Comment by alex-grover** [comment]
@alejalapeno I believe that was there before - there are different files for making the env vars available during runtime vs during the build process: https://zeit.co/docs/v2/serverless-functions/env-and-secrets

**Comment by alejalapeno** [comment]
@ajgrover looking at the git history you're correct it hasn't changed. But both of those sections are nearly word-for-word identical and both address `now dev` local availability rather than the secrets being available during build exclusively. Functionality should either be identical then, or documented how they differ.

**Comment by IEP** [comment]
> Possibly related: when deploying from my local machine I can pass env variables using `now -e MY_VARIABLE=my_value`. Also works in a local Docker container using `now -e ... --token=... `. However, on Bitbucket Pipelines with exactly the same Docker container (`node:latest`, Debian Linux 9) and exactly the same command this fails and the value of the variable is always `undefined`.
> 
> @jlbroughton88 you can downgrade using `npm -i -g now@16`, but v16 handles the build step differently.

`.env` confirm to be worked after reverting back to `now@16`

**Comment by rhino88** [comment]
For my to get my `.env` variables working with `now dev` I also needed to include the variable in my `now.json`.

Example:

In code: `const secret = process.env.SECRET_KEY`

My `now.json`:

```
{
  "env": {
    "SECRET_KEY": "@secret-key"
  }
}
```

I also defined the variable for preview/production envs using the `now secrets add secret-key foo`.

**Comment by alex-grover** [comment]
@rhino88 are you using now 17? I've had that in my now.json before as well but the variables don't come through using 17.0.3 as of last time i checked

**Comment by mjurincic** [comment]
Same issue here .env doesn't work with now dev, although it works fine in production when populated from now secrets instead overridden from .env. Example repo with .env not beeing passed to lambda in /api/ https://bitbucket.org/mjurincic-dickeys/with-now-env-dotenv/src/master/. But works if you enumerate same env variables in both .env and .env.build https://bitbucket.org/mjurincic-dickeys/with-now-env-dotenv/src/851c2edd0d299704ed5ce4bdb8b7bb128e6b2b13/?at=feature/with-env-keys-in-both-dotenv-dontenvdotbuild, which seems contrary to what documentations says (.env should override env key in now.json and .env.build overrides build.env key), not sure if its a bug or intentional .env.build replaces all but docs are outdated

**Comment by sambecker** [comment]
Looks like this might be fixed in commit https://github.com/zeit/now/commit/553ad240f01ba51a685f922f1deff8f018150927 destined for release `18.0.0`?

**Comment by danoc** [comment]
@styfle, is https://github.com/zeit/now/pull/3862 related to this issue as well?

**Comment by styfle** [comment]
@danoc No, that is unrelated. This issue is related to #3777 because Now CLI 17 changed the way `now dev` proxies requests to `next dev`.

cc @lucleray @leo

**Comment by styfle** [comment]
@mjurincic Thanks for the repro steps!

This has been fixed on the canary channel: `npm i -g now@canary`

**Comment by wyeo** [comment]
It seems the problem still exist with `now@16.7.3` and the latest `now@17.1.1` unless duplicating `build.env.MY_SECRET` and `env.MY_SECRET` as on @mjurincic example

**Comment by sambecker** [comment]
@wyeo the most recent version of `now` seems to have fixed `ENV` handling on my app. FWIW I have switched from `now dev` to `npm run dev` when testing locally. I believe I saw that recommended somewhere.

**Comment by wyeo** [comment]
@sambecker Good to know, thanks
