### ISSUE TITLE
now.json configuration file not being honored

### ISSUE THREAD

**Issue by toymachiner62** [vercel/vercel#603]
According to the [configuration](https://zeit.co/docs/features/configuration#`type`-(string)) page, if I add a `now.json` file with the contents:

```json
{
  "files": [
    "dist"
  ],

  "type": "docker"
}
```

and I have both a `package.json` and `Dockerfile`, when i execute `$ now`, it should not ask me which type i'd like to deploy and it should upload the `dist` folder even though `dist` is in my `.gitignore` file.

My `now.json` file doesn't seem to be honored as I'm getting asked which type of deployment I want:

```sh
 $ now
> Deploying ~/Sites/mysite under myusername
> Two manifests found. Press [n] to deploy or re-run with --flag
> [1] package.json	   --npm 
> [2] Dockerfile	--docker 
> Aborted
```

and i'm also getting an error that my `dist` folder doesn't exist (which this issue is resolved if i remove `/dist` from my `.gitignore` file):

```sh
$ now --docker
...
Step 2 : COPY dist /usr/share/nginx/html
> lstat dist: no such file or directory
```

**Comment by leo** [comment]
Fixed in [6.2.1](https://github.com/zeit/now-cli/releases/tag/6.2.1)!

**Comment by toymachiner62** [comment]
It's still failing to recognize the `dist` folder from my `now.json` file even though it's clearly there. Works if i comment out the `dist` folder in my `.gitignore`.

```sh
$ now -d    
> Deploying ~/Sites/mysite under myuser
> [debug] Detected `deploymentType` = `docker`
> [debug] Detected `deploymentName` = "devly"
> [debug] ignoring "/Users/myuser/Sites/mysite/dist"
> [debug] locating files /Users/myuser/Sites/mysite: 2.668ms
> [debug] Getting files: 10.375ms
> [debug] Computing hashes: 4.086ms
> [debug] /now/create: 1384.989ms
> Ready! https://mysite-leqtdzusga.now.sh (copied to clipboard) [1s]
> Initializing…
> [debug] closing agent
> Building
> ▲ docker build
Sending build context to Docker daemon 3.072 kBkB
> Step 1 : FROM nginx
>  ---> 958a7ae9e569
> Step 2 : COPY dist /usr/share/nginx/html
> lstat dist: no such file or directory
> Error! The build step of your project failed. To retry, run `now --force`.
me@mymachine.local:/Users/myuser/Sites/mysite  git:(master) $ ls
Dockerfile               e2e                     node_modules            package.json            src                     tslint.json
README.md               dist                    karma.conf.js           now.json                protractor.conf.js      tsconfig.json
```

**Comment by toymachiner62** [comment]
This bug should be opened. It's not fixe din 6.2.1.

**Comment by leo** [comment]
This issue is about the deployment type (which was fixed). [This](https://github.com/zeit/now-cli/issues/596) is the remaining issue.

**Comment by toymachiner62** [comment]
Well to be completely clear - my original question does mention both issues. It was not clear until your last comment that only one was addressed in 6.2.1.
