### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by mistakenelf** [vercel/vercel#651]
```/usr/local/bin/now -> /usr/local/lib/node_modules/now/download/dist/now

> now@6.3.1 postinstall /usr/local/lib/node_modules/now
> node download/install.js

fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/now/download/dist/download.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/now/download/install.js:19:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! now@6.3.1 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the now@6.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tknipfer/.npm/_logs/2017-06-08T13_51_56_474Z-debug.log```

I keep getting this error when trying to install. Any idea? Im using node 8.1

**Comment by nkzawa** [comment]
@leo @igorklopov https://github.com/zeit/now-cli/blob/master/download/install.js#L19 what is this for ? It looks `download.js` has no write permission if it's not owner.

**Comment by MariusAlch** [comment]
having same issue

**Comment by cfjedimaster** [comment]
Same here.

**Comment by leo** [comment]
@igorklopov Any ideas on this?

**Comment by igorklopov** [comment]
Fixed in https://github.com/zeit/now-cli/pull/663/files.
That code was useful when i ran `install.js` manually to check how download works (and `download.js` had an argument what version to download). So, useless code.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-cli/pull/663

**Comment by cfjedimaster** [comment]
I see this is closed, but it is still an issue for me. I uninstalled now (even though it didn't successfully install), then tried to install again and I get the same issue.

**Comment by leo** [comment]
@cfjedimaster We haven't published the fix yet. Will do in a second!

**Comment by leo** [comment]
Please update to [6.4.0](https://github.com/zeit/now-cli/releases/tag/6.4.0) - it should fix this issue!

**Comment by cfjedimaster** [comment]
I'm still having the same issue and can confirm it is grabbing 6.4.0.

**Comment by leo** [comment]
@cfjedimaster Have you tried `npm install now@6.4.0 -g`?

**Comment by igorklopov** [comment]
@cfjedimaster We simply removed that problematic code @knipferrc's stacktrace points to. So please provide your stacktrace from 6.4.0.

**Comment by mistakenelf** [comment]
What I had to do was change into the .config directory in my home directory, delete the entire global yarn directory and reinstall and it worked.

**Comment by leo** [comment]
Perfect! Then [6.4.0](https://github.com/zeit/now-cli/releases/tag/6.4.0) fixes the issue - you just need to clear your module cache.

**Comment by cfjedimaster** [comment]
Ok - tried npm cache clean, and still no go. Stack trace is the *exact* same except for the version #, but in case I'm missing it...

/usr/local/bin/now -> /usr/local/lib/node_modules/now/download/dist/now

> now@6.4.0 postinstall /usr/local/lib/node_modules/now
> node download/install.js

{ Error: EACCES: permission denied, open '/usr/local/lib/node_modules/now/download/dist/now'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.writeFileSync (fs.js:1287:33)
    at _callee$ (/usr/local/lib/node_modules/now/download/dist/download.js:4754:26)
    at tryCatch (/usr/local/lib/node_modules/now/download/dist/download.js:4997:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/now/download/dist/download.js:5235:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/now/download/dist/download.js:5049:21)
    at step (/usr/local/lib/node_modules/now/download/dist/download.js:6603:30)
    at /usr/local/lib/node_modules/now/download/dist/download.js:6621:14
    at Promise (<anonymous>)
    at F (/usr/local/lib/node_modules/now/download/dist/download.js:3466:28)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/now/download/dist/now' }
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! now@6.4.0 postinstall: `node download/install.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the now@6.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2017-06-12T15_39_58_237Z-debug.log
~/.config$

**Comment by leo** [comment]
@cfjedimaster Have you [fixed your npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)? If you haven't done that before, you'll most likely have to use `sudo npm install now@6.4.0 -g` to make it work... 😊

**Comment by cfjedimaster** [comment]
Boom - thank you!

**Comment by leo** [comment]
Perfect! No problem.

**Comment by Stas-Buzunko** [comment]
Tried fixing permissions, still doesn't work

**Comment by Stas-Buzunko** [comment]
It's permissions issue, for people who couldn't fix permissions, workaround to install now in project locally and run ./node_modules/now/download/dist/now
